### ISSUE TITLE
Consolidate Tools & Hotkeys

### ISSUE THREAD

**Issue by ettiSurreal** [TokisanGames/Terrain3D#122]
Raise and Lower are combined into one tool, with a toggle somewhere into UI to change between addition and subtraction.
Additionally, a modifier key should be implemented to temporarily switch to the opposite mode (it goes back to what it was before when it's let go). CTRL should be familiar for Blender sculpt mode users.

**Comment by Chevifier** [comment]
Better Idea hold control to use the alternate tool.

**Comment by TokisanGames** [comment]
In the UI, separate raise/lower buttons is the same as a combined button plus a raise/lower toggle.

I'm not opposed to defaulting to raise and CTRL for the opposite for raise/lower. The same for expand/reduce. And the same for smooth/erode.

**Comment by TokisanGames** [comment]
Currently, CTRL works as negative for Holes, Navigation, Autoshader and Foliage.

@tcoxon is working on adding a lift floor / flatten peak option that will likely go with Alt in #275 .

Here's what I'm thinking we move towards:
| Positive | Negative |
|---|---|
| <kbd>Click</kbd>: Raise | <kbd>Ctrl + Click</kbd>: Lower
| <kbd>Alt + Click</kbd>: Expand | <kbd>Ctrl + Alt + Click</kbd>: Reduce
| <kbd>Shift + Alt + Click</kbd>: Lift floors | <kbd>Shift + Ctrl + Alt + Click</kbd>: Flatten peaks
| <kbd>Shift + Click</kbd>: Smooth | <kbd>Ctrl + Shift + Click</kbd>: Erode (To be implemented)

The alternate mode buttons are hidden, and are replaced when the keys are pressed.

Raise/Expand strengths need refinement. They're fine when far out, but up close they're too strong. I think their strength needs to adjust based on distance. Raise should be lessened *0.1 to match Expand, and/or adjusted based on distance to the camera.

For the rare tablet user (we have at least one), we can detect if we're on an android/ios/(touch enabled?) system, and enable modifier toggle buttons on the toolbar at the bottom of the stack to enable CTRL, SHIFT, ALT. The toolbar because they modify it, and we'll have a lot more room after hiding the negatives.

**Comment by TokisanGames** [comment]
With #409 and #418, we have expanded support for CTRL to invert all operations it can:
* Regions
* Raise/lower
* Expand/reduce sculpting
* Paint color
* Paint wetness
* Autoshader
* Holes
* Navigation
* Foliage

Also Alt provides a lift floors and reduce peaks mode shown in #409.

**Comment by TokisanGames** [comment]
I've adjusted the default brush settings and application in #444. I'm considering dropping the expand/reduce brushes. After these changes, are they different enough from raise/lower that they're worth keeping? Please test out the build and give me feedback.

**Comment by TokisanGames** [comment]
#444 removes expand/reduce. Now we respond to ctrl(negative), alt (lift/flatten), and shift(smooth) keys.
