### ISSUE TITLE
Adjustable mesh density

### ISSUE THREAD

**Issue by TokisanGames** [TokisanGames/Terrain3D#131]
Our mesh vertices are every 1 unit. The Witcher 3 uses 0.5 for their clipmap terrain, which I'd like to copy. Lower end hardware might benefit from 2+.

This would allow using a 1024px map for a 512m world, or a 2048m world instead of the current 1024px = 1024m world.

**Comment by Saul2022** [comment]
Maybe as of a . later pr, if  i understand this correctly you can make the density decrease automatically  when more  far away   while maintaining the distance to save some performance.

**Comment by nanodeath** [comment]
I'm going to take a look at this. I've figured out how to make the terrain scale visually, I just need to do a bunch of testing to make sure the physics and terrain sculpting/painting works. Then I'll send a PR assuming that's all working.

---

One open question, though. When changing the terrain size, the height scale is incorrect. That is, when changing from 1024 to 2048, the terrain is half the height it should be. Do we want to try to do anything about that? I can think of three options:

1. Explicitly update the height scale when changing the terrain size. By this I mean when going from 1024 to 2048, automatically change the height scale in the inspector from, say, 1000 to 2000 (same factor as the terrain size change).
2. Implicitly update the height scale. If the user specifies height scale 1000 and terrain size 2048, we internally treat it as if they'd specified 2000 for height. That is, we calculate a multiplier based on the terrain size vs 1024 and apply that when using height.
3. Do nothing, make the user specify the height each time. And...frankly users shouldn't be importing terrain all that often (hopefully).

Each of these have merit. 1 is nice because it usually Just Works but users keep control if they want to specify the exact height. 2 is nice because it means if I have two heightmaps of the same logical region, but different sizes, I can give them the same height scale and that Just works. 3 is kinda nice because there's no magic involved.

IMO there should be a _little_ magic here. I think I'm personally leaning slightly towards 2 because I already have problems forgetting which height scale I import my terrains at, and last thing I want is to remember more numbers.

Thoughts?

**Comment by nanodeath** [comment]
Okay, I'll join the Discord when I can...

But I was able to revert [this commit](https://github.com/TokisanGames/Terrain3D/commit/ebf9df002d4dfe44165191f57b7b0b1899af8bd4) and get that working with a 1-line code change. Is that approach fundamentally flawed or something?

**Comment by TokisanGames** [comment]
That commit came out of #77, and you can read about why it was temporarily disabled. Not the same thing as mesh density, in this ticket.

Subsequent changes may allow other region sizes to work, but it needs further testing before it can be enabled again.

**Comment by TokisanGames** [comment]
Implemented in #296
