### ISSUE TITLE
Support occlusion baking 

### ISSUE THREAD

**Issue by TokisanGames** [TokisanGames/Terrain3D#177]
From @SlashScreen

Looking into it, it looks like adding an occlusion mesh to the rendering server to allow the terrain to act as an occluder may be relatively simple. You can [add a mesh directly to the rendering server](https://docs.godotengine.org/en/stable/classes/class_renderingserver.html#class-renderingserver-method-occluder-create) with this function and the one below it. It could go somewhere in [these blocks](https://github.com/outobugi/Terrain3D/blob/b56cda5323e8e2d17a126e6d93375c2340195918/src/terrain_3d.cpp#L202), and just upload the static mesh. However, having it update too often could cause performance issues, since it has to build a BVH.

-------

My comments
It may not be necessary due to the nature of a clipmap terrain that already lods the distant terrain and hides everything beyond. But it's worth considering if it is worth it. Occluders could hide our enemies and cities between mountains. But manual shapes under mountains can also accomplish this.

**Comment by SlashScreen** [comment]
> It may not be necessary due to the nature of a clipmap terrain that already lods the distant terrain and hides everything beyond. 

This may be true for the terrain, but it is not true for other objects apart from the terrain. A hill in the terrain does not cull, say, trees behind it without an occluder. I've checked - at least with occlusion culling on, which I must have to tame complex interiors in my game.

>  But manual shapes under mountains can also accomplish this.

Indeed, it can. In some cases, it may be preferable, since complex occlusion meshes *could* be an issue in extreme cases. This is what I'm doing now. But I can tell you it's very tedious and error prone.

**Comment by tcoxon** [comment]
I have [some code](https://github.com/tcoxon/Terrain3D/commit/a68cee16cad44d82b55c74acbaf8bedcfa010454) that can 'bake' an ArrayMesh or Occluder3D mesh from Terrain3D at a configurable LOD. Happy to donate this back. Let me know if I should clean this up and submit a PR.

**Comment by TokisanGames** [comment]
@tcoxon Oh that looks great. Yes please. Can this mesh or some of these support functions also be used for the navigation server?

I'd like some documentation in the code and a usage writeup for the wiki.

Where did you place the bake menu button?

I don't think we need the .res in the commit.

Undo action name should match the other operations, `Terrain3D Bake Occluder Mesh`:
String action_name = String("Terrain3D ") + OPNAME[_operation] + String(" ") + TOOLNAME[_tool];

If `_get_vertex()` needs to be standalone and static, it should go in Util. But if only Terrain3D is going to use it, then it should just be a private var in that class, and placed in the section labeled private.

**Comment by tcoxon** [comment]
@TokisanGames I'll clean it up, add documentation, and submit a PR then.

The bake button appears in the top menu of the spatial editor, along the same row as the 'Bake Navigation' button that appears for NavigationRegion3D nodes.

Since you asked about the navigation server, I've actually been investigating options for navigation today. This might indeed form part of the solution, but I need more time to fully figure it out.

**Comment by SlashScreen** [comment]
@tcoxon I have done a fair amount of research on the topic of navigation servers, and compiled it [here](https://github.com/users/TokisanGames/projects/3?pane=issue&itemId=36455299). Good job on the occlusion mesh thing; That will be very helpful to me.
