### ISSUE TITLE
Support standard Godot materials

### ISSUE THREAD

**Issue by krazyjakee** [TokisanGames/Terrain3D#199]
This plugin introduces a duplicate set of steps in the asset pipeline. Godot already has tools and settings to manage textures, normal, height and rough maps etc. Those should be supported when adding paintable textures to the pallet.

**Comment by TokisanGames** [comment]
I think if you were implementing it, you would find as we have that StandardMaterials are both inadequate and overkill for terrain.

Inadequate because it doesn't provide all the functionality we need. Materials are just a shader and we'd have to rewrite it anyway.

Overkill because we don't need SSS, refraction, rim, clearcoat, backlighting, and many other features on the terrain. If your thought is that doing this would allow one to use any and all features of a StandardMaterial on the terrain, then you really haven't thought about the complexity of implementation.

The base material shader is integrated into the renderer and is designed for 1 material. It is not designed to merge 32 materials. That code doesn't exist in the engine anywhere. Someone has to write it. We wrote a far, far simpler version focused on the needs of a terrain. Supporting the entire base material would make our already complex shader 10x more complex for unnecessary features like vertex color, billboard and the others I mentioned.

Ignoring implementation, we could possibly take in materials then take the textures and settings we need from it. We'd only use the needed features, which means this choice would provide the user with 50 material options yet only 10 would be functional and they'll have to guess or read the docs to figure out which ones work. That's not an improvement on usability.

Finally, there are things needed that are not in the current terrain shader. Some will make their way into the default shader, others can be added by custom shaders and custom uniforms. For instance, we have a lava texture with emission. It would be a big waste of memory and processing to enable emission for all textures. But a custom shader and custom uniform will allow us to add an emission texture for that one material. You could do the same thing with metal.

So, no standard materials will not be used. A better request would be to express your need, rather than an implementation. Here are things on the roadmap that might fulfill needs:
* #125 - Easier workflow preparing textures
* #148 - Sharing textures among levels 
* #86
* #65

**Comment by krazyjakee** [comment]
Great explanation!

As mentioned the main issue is the asset pipeline workflow so #125 seems most appropriate.
