### ISSUE TITLE
Expose next_pass value as a property of the ground material

### ISSUE THREAD

**Issue by SkellySoft** [TokisanGames/Terrain3D#206]
Hi. Cory from TokisanGames mentioned I should put this here, so that's what I'm doing - essentially, in the past I've utilized a basic "low lying fog" technique using a semi-transparent repeating fog texture, and a next_pass on the material for the terrain mesh beneath the player that essentially just scrolls it in one direction, to add a nice layer of mist that hugs the floor. It looks really great, only thing is I can't do this with my Terrain3D project because next_pass doesn't appear to be exposed, so it's not possible at present.

I was told to add the shader code I used for the scrolling mist/fog effect, it's incredibly basic but I shall include it here all the same.

```gdscript
shader_type spatial;
render_mode diffuse_burley,specular_disabled,depth_prepass_alpha;

uniform float from_ground_dist = 1.0;
uniform float fog_res = 30;
uniform sampler2D fog_texture;
uniform vec2 Direction = vec2(0.15, -0.33);
uniform float speed = 0.5;

void fragment(){
vec3 final_fog_layer = texture(fog_texture, UV + (Direction * TIME * speed)).rgb * fog_res;

ALBEDO = final_fog_layer;

METALLIC = 0.0;
ROUGHNESS = 1.0;
ALPHA = 0.25;
}

void vertex() {
VERTEX+=NORMAL*from_ground_dist;
}
``` 

- SkellySoft

**Comment by TokisanGames** [comment]
I tested exposing render priority and next pass today. The first does nothing. The second doesn't work as desired. It breaks the main shader.

Here it is in use. It looks like this with a blank shader or yours. The square lines show where the lods are broken due to the vertex shader. Even with the vertex portion disabled, it no longer breaks the lods, but it's still white like this. I have no idea why it only affects ground level vertices. I tried copying the vertex shader from the main shader over but it would require copying over the uniforms and other texture arrays. 

![image](https://github.com/TokisanGames/Terrain3D/assets/632766/36aa81b9-dc34-49e5-ad27-b4b492862150)

Looking at this shader though I don't see why it can't just be added into the first pass of a custom shader. All you need are custom uniforms in #216. Once custom uniforms are finalized I'll try this shader there.

**Comment by TokisanGames** [comment]
I tried this on a regular mesh, and it didn't work the way it was described. It overwrote the color of the original shader. It should be using a blend mode for a second pass. It looks more normal with `blend_add` since we want it lighter. 

I see no value in ground distance as it either creates z-fighting artifacts, or a ghost image of the mesh, so I removed it.

![image](https://github.com/TokisanGames/Terrain3D/assets/632766/dcfcf6ea-901a-41f1-9db0-dcba7bdedbaf)

![image](https://github.com/TokisanGames/Terrain3D/assets/632766/6557fb62-0e10-42a2-96a2-0357774205c2)

I think this works much better. It can easily be added to the first pass in a custom shader in Terrain3D. 

```glsl
shader_type spatial;
render_mode diffuse_burley,specular_disabled,blend_add;

uniform sampler2D fog_texture;
uniform float alpha : hint_range(0, 1) = 1.;
uniform float thickness : hint_range(0, 10) = 1.;
uniform float scale : hint_range(0.001, 100) = 1.;
uniform vec2 direction = vec2(0.15, -0.33);
uniform float speed : hint_range(0, 10) = 1.;

void fragment(){
	vec3 final_fog_layer = texture(fog_texture, scale * (UV + (direction * TIME * speed * .1))).rgb;
	ALBEDO = clamp(final_fog_layer * thickness, vec3(0), vec3(1));
	ROUGHNESS = 0.0;
	SPECULAR = 0.0;
	ALPHA = clamp((final_fog_layer.r) * alpha, 0, 1);
}


```

![image](https://github.com/TokisanGames/Terrain3D/assets/632766/6b7f7f7b-9151-4b37-8916-157fc1285744)

Now that I'm using blend_add and I removed the vertex shader it might be worth trying to expose next_pass again. I will if any shaders can work, but won't if they break it.
