### ISSUE TITLE
Texture Corruption Issue?

### ISSUE THREAD

**Issue by matthewjamesr** [TokisanGames/Terrain3D#223]
Hello,

I am following the steps to color-pack into a DDS file. I can import the texture and paint it, but I get the corruption/visual distortions in the image below. The green bleeds from my grass texture into the rocks, and the rocks bleed into the grass. As I move away the distortions disappear. Any help would be much appreciated!

![image](https://github.com/TokisanGames/Terrain3D/assets/303321/a527d3b4-c1ad-4ee5-87c2-f945e1bade64)

**Comment by TokisanGames** [comment]
I can't help without any information about your platform, renderer, versions, what you've tried, what your textures look like and info about them, what your channel packed textures look like after you've opened them up again, texture settings, etc.

The texture blocks looks like #137 

That grey strip is an artifact on the region border #185 and since it's that big you must be zoomed in very far.

Do you have any problem with the demo textures on this system? If not, it's the process or your textures.

**Comment by TokisanGames** [comment]
Closing due to no response and not reproducable. Most likely a mistake made during texture creation.

Feel free to comment more if you're ready to troubleshoot and provide information, and we can reopen.
