### ISSUE TITLE
Importing 256th region doesn't work

### ISSUE THREAD

**Issue by langyaWang22** [TokisanGames/Terrain3D#233]
When importing a height map (16384x16384), an error occurred at the location shown in the figure, and the error was constantly reported when selecting terrain nodes.
![jpg](https://github.com/TokisanGames/Terrain3D/assets/16213052/df84de37-69b8-4ace-bdc2-0a8467f13dac)

**Comment by TokisanGames** [comment]
What version or commit of Terrain3D?

You stated "when importing", but this screen shot is not of the importer, so it's not during the import process. Did importing produce any errors? How did you import the data then get it in this other scene? AFAIK it's not possible to save 16k resource files. #159 

You wrote "an error". Are you referring to the visual artifact on screen or the 44k errors? What exact process did you go through to do this? We've had [16k imports ](https://twitter.com/MiroHorvath/status/1683526707150503945) just fine without issue.

**Comment by langyaWang22** [comment]
> What version or commit of Terrain3D?
> 
> You stated "when importing", but this screen shot is not of the importer, so it's not during the import process. Did importing produce any errors? How did you import the data then get it in this other scene? AFAIK it's not possible to save 16k resource files. #159
> 
> You wrote "an error". Are you referring to the visual artifact on screen or the 44k errors? What exact process did you go through to do this? We've had [16k imports ](https://twitter.com/MiroHorvath/status/1683526707150503945) just fine without issue.

Version terrain3d_ 0.8.3-alpha_ Gd4.1.1
Sorry, I didn't explain it clearly. There was a problem during the import process.
Import error occurred in one corner of the terrain (X.MAX, Z.MAX)
In addition, when selecting the Importer node and moving the mouse to the error area, the following error will occur:
 core/io/image.cpp:3265 - Index p_x = 1315 is out of bounds (width = 1024).
  core/io/image.cpp:3265 - Index p_x = 1316 is out of bounds (width = 1024).
  core/io/image.cpp:3265 - Index p_x = 1317 is out of bounds (width = 1024).
  core/io/image.cpp:3265 - Index p_x = 1318 is out of bounds (width = 1024).
  core/io/image.cpp:3265 - Index p_x = 1319 is out of bounds (width = 1024).
  core/io/image.cpp:3265 - Index p_x = 1320 is out of bounds (width = 1024).
  core/io/image.cpp:3265 - Index p_x = 1321 is out of bounds (width = 1024).
  core/io/image.cpp:3265 - Index p_x = 1322 is out of bounds (width = 1024).

![jpg](https://github.com/TokisanGames/Terrain3D/assets/16213052/2b71fcf6-8e5a-4a62-8c98-fa1434657bc1)

**Comment by TokisanGames** [comment]
In the current master branch and Godot 4.1.2, I'm able to import 16k x 16k without error messages. There were artifacts outside of the global region boundary, fixed in [4fc9b4c](https://github.com/TokisanGames/Terrain3D/commit/4fc9b4c539611bae0e00e8b6cb595b92f75bca10), but that is different than the issue reported here. 

The only problem is that last added region shows as flat. There's likely an array index error somewhere. When that is fixed, this ticket will be closed.

Also note:
* This large terrain can't be saved (so the scene can't be run) due to an engine bug documented in #159. 
* Collision takes up too much memory #161

**Comment by TokisanGames** [comment]
The region_map is an array of 256 bytes, which holds the ID number of each region. Since there are 256 regions available and each byte can hold 0-255, this would work fine. However we currently store 0 if no region is present. So, we need a range of 0-256, or 257 values. Most likely the last region is being created and stored with region id 256, which wraps to 0, which means no region. 

We'll have to figure out a different way to either ID the regions or store the IDs. Perhaps either making it an array of 2 byte ints, or storing the presence in an array of bits, which could fit in 8 bytes. Probably the former so we can expand to much larger terrains later.

**Comment by TokisanGames** [comment]
Fixed in #250 

![image](https://github.com/TokisanGames/Terrain3D/assets/632766/0060c7b5-2aed-4b2b-8b46-5f7b985fd871)
