### ISSUE TITLE
Worldmachine bitmaps not importing correctly

### ISSUE THREAD

**Issue by AjaniBilby** [TokisanGames/Terrain3D#237]
I assume this is user error, but I've read over the wiki many times and can't work this out.  
When I put the bitmap into the `color file` `import file` field it does nothing, and when I drag it into the `textures` pannel it appears transparent.  
![image](https://github.com/TokisanGames/Terrain3D/assets/11359344/58daa789-304c-4b05-92ef-36e28c3b4d41)

The above test is done using the example project supplied in the release of `v0.8.3` to make sure it's not caused by any side-affects of how my actual project is setup

Attached files incase it's something weird to do with the specific encoding of how world machine outputs files  
**Heightmap**
![New Project Height Output-1025](https://github.com/TokisanGames/Terrain3D/assets/11359344/546fd639-d0a8-4097-9e3e-045d9c1548aa)
**Bitmap**
![New Project Bitmap Output-1025](https://github.com/TokisanGames/Terrain3D/assets/11359344/e7f0c504-4d39-4336-8272-7a48bc838e1c)

*These are intentionally low res outputs while I'm experimenting*

**Comment by TokisanGames** [comment]
The texture list is for painting textures. Empty the list unless you are going to paint. If you want to use a single texture for the whole terrain use the colormap. 

Disable checkerbox debug view in the material and enable the colormap. It's setup for painting textures, not GIS type work like this. But these clicks will set it up. 

There were updates to the import process that make importing GIS maps more intuitive recently. Download and build the current master branch, or get the latest compiled artifact from the actions tab.

**Comment by AjaniBilby** [comment]
I did use the colour map and that didn't work, also using the brush tool didn't work, also the latest windows build is the one in the releases because you cancelled the latest windows build action.

Also I realised for more detailed heightmaps the `.tres` is over 1GB, so I think I'll just have to try and use WorldMachine's `obj` tiling along with splatting.

**Comment by TokisanGames** [comment]
>  the .tres is over 1GB 

Don't save as .tres, which is text. The directions specifically say save in binary using .res. Obj is also text. 

> the latest windows build is the one in the releases because you cancelled the latest windows build action.

The building is automatic. Some fail due to problems with Github, but there are tons of builds available for the main branch that are more recent than the releases.

This is the most recent, and it was successful. Download this artifact. 

https://github.com/TokisanGames/Terrain3D/actions/runs/6682416126 

> I did use the colour map and that didn't work

Import into colormap. Change the debug views to display the colormap. The importer in this build does this automatically. 

> using the brush tool didn't work

Not sure which tool you used, but if it was texturing, it won't work unless you have textures.
