### ISSUE TITLE
Player does not collide with ground in demo

### ISSUE THREAD

**Issue by Xiode** [TokisanGames/Terrain3D#261]
### Terrain3D version

Terrain3D v0.8.4-alpha_gd4.1.3

### Godot version

v4.2.stable.mono.official [46dc27791]

### System information

Godot v4.2.stable.mono - Windows 10.0.19045 - Vulkan (Forward+) - integrated AMD Radeon(TM) Vega 8 Graphics (Advanced Micro Devices, Inc.; 27.20.15002.8001) - AMD Ryzen 5 2500U with Radeon Vega Mobile Gfx (8 Threads)

### Is the issue reproducable in the demo?

Yes

### Issue description

In the demo, the player does not collide with the ground. Fresh install of Godot 4.2 and Terrain3D v0.8.4-alpha_gd4.1.3

### Logs

Console: 
```Godot Engine v4.2.stable.mono.official.46dc27791 - https://godotengine.org
Vulkan API 1.2.164 - Forward+ - Using Vulkan Device #0: AMD - AMD Radeon(TM) Vega 8 Graphics

ERROR: FATAL: Index p_index = 0 is out of bounds (shapes.size() = 0).
   at: get_shape (servers/physics_3d/godot_collision_object_3d.h:124)```

**Comment by TokisanGames** [comment]
Did you use the version for 4.2 linked in the release notes? That version works perfectly with the 4.2 releases both mono and non-mono versions.

I cannot reproduce that error with fresh installs of everything above.

You can try 4.1.3 with the 4.1.3 terrain3d release. This build also works in 4.2 but has error spam.

Otherwise, you'll need to debug the engine and see what is actually occurring on your system at this point:
https://github.com/godotengine/godot/blob/0bf12956a10d216c46368f26b00f6999d000c1d8/servers/physics_3d/godot_collision_object_3d.h#L124

We are not calling get_shape(), so you need the callstack to determine who and what is.

**Comment by TokisanGames** [comment]
Since there's been no response, and this isn't reproducible, this issue will be closed soon. Respond if you want help, after you've tested the other versions suggested.

**Comment by TokisanGames** [comment]
Closed due to no response and not reproducible. It can be reopened if you wish to troubleshoot. There's a new version out, try that as well as the other things mentioned.
