### ISSUE TITLE
Display brush names when expanding brush panel

### ISSUE THREAD

**Issue by Flynsarmy** [TokisanGames/Terrain3D#299]
### Description

A nice usability enhancement for those who are newer to the terrain tools would be to show the brush names when the brush panel has room for them. Blender is a great example of a feature like this in action:

https://github.com/TokisanGames/Terrain3D/assets/334808/5ee79570-009b-4332-83df-737e2739a445

**Comment by TokisanGames** [comment]
Due to #417 and its fix #472, this isn't something we can easily do. In order to support vertically short displays (eg mobile), we now use a flow container for buttons. Sliding out the panel and instantiating labels it a bit contrary to having buttons flow around the screen size. The buttons have tooltips for new people already, so not having this feature isn't a huge inconvenience.
