### ISSUE TITLE
In the CodeGenerated demo, pathfinding is jerky

### ISSUE THREAD

**Issue by JekSun97** [TokisanGames/Terrain3D#394]
### Terrain3D version

v0.9.2-dev

### System information

Godot v4.2.2.stable - Windows 10.0.19045 - Vulkan (Forward+) - dedicated Radeon RX 560 Series (Advanced Micro Devices, Inc.; 31.0.14001.45012) - Intel(R) Core(TM) i5-4570 CPU @ 3.20GHz (4 Threads)

### Is the issue reproducable in the demo?

Yes

### Issue description

When I started the CodeGenerated.tscn demo, the agent’s path search was intermittent with long delays, there were times when the agent stood next to me and for about 6 seconds could not find the path to me

https://github.com/TokisanGames/Terrain3D/assets/130399274/418d7c81-55e4-4728-9baa-b0a35c28b16e

### Logs

Empty

**Comment by tcoxon** [comment]
There are a few reasons for this, but it's not a bug. It's a lot clearer why it happens if you make navigation visible:

![image](https://github.com/TokisanGames/Terrain3D/assets/165720/fadbc0b4-5f68-4d6a-9dd8-6f4c1ffd5a27)

https://github.com/TokisanGames/Terrain3D/assets/165720/d1867aca-105f-45ea-9171-cde7d0e39bb9

The blue mesh that covers the ground is the navigation mesh. The RuntimeNavigationBaker script periodically rebakes this on a thread. You can adjust the "bake cooldown" on the baker to do this more frequently, but you'll still run into the fact that baking navigation is just slow. This is why editor/compile-time baking navigation is usually a better option for games (where that can be done).

However, runtime baking can still be usable. There are a few things you can do to speed it up, or work around the slowness:

- You can create a set of fallback behaviors that get used when proper navigation isn't possible. In this way, you can make AI degrade when waiting for nav, or out of range of the nav mesh, without completely failing. This approach comes with its own drawbacks and limitations, and how you go about it depends on what's acceptable for your project. In my own project, agents bee-line when off-mesh. This works fine for me.
- You can reduce the speed of the player character. Delays happen frequently in the demo because the player can move across the mesh so rapidly.
- You can reduce the size of the baked mesh to make it cheaper to bake (`mesh_size`).
- You can increase the size of the cells (i.e. reduce the resolution of the navmesh), defined in the NavigationMesh template (`cell_size`), to reduce the amount of work to do. But note that if you increase it too far, obstacles may hide within a cell and break your navigation. You can write fallback behaviors for that, or you can ensure your obstacles are all larger than the cell size.

A second, smaller delay is due to how frequently the navigation agent updates its path. You can do this more frequently by adjusting the `RETARGET_COOLDOWN` constant (currently 1.0 seconds), but if you have a lot of agents that's going to come with a performance cost.

**Comment by JekSun97** [comment]
Thanks, I think this should be mentioned somewhere in the documentation

**Comment by TokisanGames** [comment]
@tcoxon Thanks for looking at it and providing the explanation.

Docs updated in https://github.com/TokisanGames/Terrain3D/commit/15ff7e5b89dfc58fd6d9336924679a6780ef111e
