### ISSUE TITLE
Mostly green texture breaks other textures

### ISSUE THREAD

**Issue by LarrikinDan** [TokisanGames/Terrain3D#399]
### Terrain3D version

v0.9.1

### System information

Godot v4.2.1.stable.official [b09f793f5]

### Is the issue reproducable in the demo?

Not applicable

### Issue description

I was adding some coloured square textures with basic hsv noise, they were the exact same settings in GIMP just using using the Colorize tool to change the hue for each before exporting.

I was dragging these into the albedo texture area but if the image was mostly green it caused the terrain itself to display plain white (regardless of which texture slot I added the green albedo to) and threw this error twice:

```core/variant/variant_utility.cpp:1091 - Terrain3DTextureList::_update_texture_data: Texture ID 5 albedo format: 19 doesn't match first texture: 17```

This doesn't happen if I change the texture to include another colour such as a red stripe. But as long as the colour is green on the whole texture it throws the error.

5 successfully assigned non green textures
![image](https://github.com/TokisanGames/Terrain3D/assets/103293201/2c61c274-baa3-46b6-962e-b62fb2c2783c)

After uploading neongreen.png
![image](https://github.com/TokisanGames/Terrain3D/assets/103293201/040d263a-905d-4632-b2a8-74e55a74e234)

Undoing that, and uploading seafoam.png
![image](https://github.com/TokisanGames/Terrain3D/assets/103293201/b0c7a735-0994-43e8-8843-920c58b12091)

Undoing that, uploading newseafoam.png (which has a red stripe through it)
![image](https://github.com/TokisanGames/Terrain3D/assets/103293201/994f01d7-53fb-4edc-a46a-50f347667526)

disclaimer: I tried using the demo to test but it had issues where I couldn't even enable the terrain3D plugin. The advice I could find to resolve said that "I hadn't installed it properly" but since it was the demo project I downloaded from the main files I couldn't be bothered to try and debug that too.

Also of note, the 'Setting up textures' link at the top of this issue form gives me a 404
![image](https://github.com/TokisanGames/Terrain3D/assets/103293201/4a2fe0b5-1e3e-4931-afb2-2085d4d161fa)

**Comment by TokisanGames** [comment]
> core/variant/variant_utility.cpp:1091 - Terrain3DTextureList::_update_texture_data: Texture ID 5 albedo format: 19 doesn't match first texture: 17

The message is quite explicit: The first texture you have in the list is [format 17](https://docs.godotengine.org/en/stable/classes/class_image.html#enum-image-format). The texture you just added as ID 5 is format 19. They don't match. Either use the old format or the new format, or any other format, as long as they are all identical. These specifications [are documented](https://terrain3d.readthedocs.io/en/latest/docs/texture_prep.html).

> This doesn't happen if I change the texture to include another colour such as a red stripe. But as long as the colour is green on the whole texture it throws the error.

The problem lies entirely in how you're creating the texture. We can't control that. We only use what you give us. If you are using PNGs (which are image files, not textures files), then you are instructing Godot to create the textures on your behalf using its texture creation library using the settings you specified on the Import panel. You can adjust those settings. Or you can make DDS files and take Godot's texture library out of the picture. Godot doesn't convert DDS textures.

Godot's texture creation library sucks, tbh. It makes automated decisions that are poor choices in some instances. Most likely you've selected a color combination that is triggering one of these odd cases in the compression library and Godot has chosen a different texture format than all of the others, for you. Since green is perceived differently than other colors, I vaguely recall seeing something about Godot changing formats based on it/green/perceptual values??

In any case, you're responsible for knowing what texture files you have and give us. You can double-click any image file and godot will tell you the format and size of any image in the inspector. We require them to all be the identical format and size (because Godot requires it for what we're doing with those files).

> I tried using the demo to test but it had issues where I couldn't even enable the terrain3D plugin. 
> I couldn't be bothered to try 

We're here to help when you are willing. We have thousands of users at this point, so yes if you can't enable the demo on your system, you didn't work through the installation instructions properly. The console reports specific error messages that we can use to help you troubleshoot.

**Comment by LarrikinDan** [comment]
I'm pretty new to Godot and game dev in general. Things that seem "pretty explicit" to you are completely opaque to me. I was just trying to help mate, no need to be condescending. In the future I'll just assume I'm being a dummy and not bother I guess.

re: demo I followed your guide to a T, and got my tutor to double check. idk what to tell you but opening your demo project it says that there are missing dependencies. The advice I can find specifically about that issue, being that the files are in the wrong location, wasn't the case, and even hooking them back up to the right files did nothing. The project couldn't enable the plugin because there were "errors in the script", but the only errors in the script were that it couldn't find the Terrain3D node because I couldn't enable the plugin because there were errors in the script.

Anyway, thanks for the info.

**Comment by TokisanGames** [comment]
> re: demo. idk what to tell you but opening your demo project it says that there are missing dependencies. 

> The project couldn't enable the plugin because there were "errors in the script", but the only errors in the script were that it couldn't find the Terrain3D node because I couldn't enable the plugin because there were errors in the script.

I offered to help. When you run Godot with the console executable, and open our demo it will show logs and error messages. We need those exact messages from the beginning of the run. I can then properly interpret the messages. There aren't errors in the script. It doesn't recognize the compiled library, possibly because it's not in the correct folder, or not on your system at all.

**Comment by novac07** [comment]
Why the hell am I getting emails like this?

În lun., 10 iun. 2024 la 05:05, Cory Petkovsek ***@***.***> a
scris:

**Comment by TokisanGames** [comment]
@novac07 No one tagged you in this thread. If you want Github to stop sending you emails click the unsub link in the email you just responded to or click the unsub button on the webpage.
