### ISSUE TITLE
Bottom bar disappears when using plugin

### ISSUE THREAD

**Issue by JekSun97** [TokisanGames/Terrain3D#417]
### Terrain3D version

v0.9.3-dev

### System information

Godot v4.2.2.stable - Windows 10.0.19045 - Vulkan (Forward+) - dedicated Radeon RX 560 Series (Advanced Micro Devices, Inc.; 31.0.14001.45012) - Intel(R) Core(TM) i5-4570 CPU @ 3.20GHz (4 Threads)

### Is the issue reproducable in the demo?

Not applicable

### Issue description

When the Terrain3D tool window is active and we click on any of the buttons on the bottom panel, for example Output, the bottom panel goes out of view of the window, which makes it impossible to open one of the windows until we switch to any other node except Terrain3D

Screen resolution: 1600x900

Demonstration of the problem:
https://youtu.be/twCqcZVWZ88

### Logs

...

**Comment by TokisanGames** [comment]
#418 removes 3 buttons, hiding them behind a CTRL press

**Comment by JekSun97** [comment]
@TokisanGames 
Selecting the "Spray Overlay Texture" tool also shifts the Inspector to the right a lot.

Here's a full screenshot:
![2](https://github.com/user-attachments/assets/255cd4bf-8045-44a6-8def-dbead388e47d)

**Comment by TokisanGames** [comment]
It's all of the options on the bottom bar that move the inspector, and Godot has a bug where it moves it off screen instead of scales it. Moving the toolbar down to the bottom like I suggested earlier probably won't work well as it will just push everything to the side. 

With such a small screen, you could reduce your side bars, consolidating them into one column instead of two.

I'm not sure how to redesign the UI to be usable for most people, yet accommodate tiny screens and godot's UI bugs.

**Comment by TokisanGames** [comment]
#444 removes Expand/Reduce. 4 buttons in total have been taken out, but we probably won't remove any more. Maybe we can look at alternate layouts.

**Comment by KoBeWi** [comment]
You can use FlowContainer instead of BoxContainer for toolbars.

**Comment by TokisanGames** [comment]
@KoBeWi Excellent, thanks for letting us know.

Completed in #472
