### ISSUE TITLE
Godot's .intersect_ray() detection appears to be buggy on Terrain3D, differs from Terrain3D's get_height() in some rectangles 

### ISSUE THREAD

**Issue by ell1e** [TokisanGames/Terrain3D#453]
### Terrain3D version

0.9.2

### System information

Godot v4.2.2.stable - Freedesktop SDK 23.08 (Flatpak runtime) - Wayland - Vulkan (Forward+) - integrated AMD Custom GPU 0405 (RADV VANGOGH) () - AMD Custom APU 0405 (8 Threads)

### Is the issue reproducable in the demo?

Not applicable

### Issue description

Godot's .intersect_ray() detection appears to be buggy on Terrain3D, differs from Terrain3D's get_height() in some rectangles:

Here's a scan of vertical rays shot down all over the terrain via `node.get_world_3d().direct_space_state.intersect_ray`:

![Screenshot_20240811_203258](https://github.com/user-attachments/assets/e8026c39-d299-4bad-ba12-54b903efd312)

As you can see, two weird rectangles don't seem to be detected correctly, I added some line to show where:

![Screenshot_20240811_203258_2](https://github.com/user-attachments/assets/78eae046-1153-498e-9c9e-bc0a0b179e7a)

When using Terrain3D's `terrain_node.storage.get_height`, there is no such gap in the detection:

![Screenshot_20240811_203203](https://github.com/user-attachments/assets/e2560d05-e6a5-4dea-a7cb-30182d9afbe4)

Here is the detection code we use:
```

			var origin = Vector3(posx, 999999, posz)
			var target = Vector3(posx, -999999, posz)
			var height
			if not use_physics_ray:
				height = terrain_3d_node.storage.get_height(
					Vector3(posx, 0, posz)
				)
			else:
				var query = PhysicsRayQueryParameters3D.create(
					origin, target)
				query.set_collision_mask(1)
				query.collide_with_areas = true
				query.collide_with_bodies = true
				query.hit_back_faces = true
				query.hit_from_inside = true
				var collision = space_state.intersect_ray(query)
				height = min_y
				if collision:
					height = collision.position.y
			_height_field[i + k * slices_x] = height

```
My apologies if this is some obvious issue on our side, but we looked at this with two people and couldn't quite figure out a reasonable cause for this. And sorry that we didn't test the demo, our code wasn't that quick to transfer over.

**Comment by ell1e** [comment]
The log was too long for the form, so here it is attached separately:

[terrain_debug_log.txt](https://github.com/user-attachments/files/16575786/terrain_debug_log.txt)

**Comment by TokisanGames** [comment]
Godot's physics is undoubtedly buggy. You should also test jolt and consider using it for release. Also test Godot 4.3rc3.

You're more likely to encounter bugs when you use extreme values, like running 2 million meter long raycasts on presumably a single precision build. Since your terrain isn't that tall, use more reasonable values. 

You could test the code you pasted here in the demo in a few minutes. 

Please show a screenshot of visible debug collision. If it matches the mesh, or jolt works, it's not our issue. We only provide the collision shape to Godot, we don't calculate physics. 

Collision is a physics calculation. Get_height is not physics at all. Read our `latest` collision document.

**Comment by ell1e** [comment]
For what it's worth, we tried way shorter rays which doesn't fix it. Longer rays missing intersects seems like in a bug in itself if that's the case, but I guess that's not up for debate here. I'm aware get_height isn't for collision, but it provided a good reference for the expected result.

I'll have to look into how debugging collisions in godot works and get back to you, I haven't tried that before.

**Comment by TokisanGames** [comment]
> Longer rays missing intersects seems like in a bug in itself if that's the case, but I guess that's not up for debate here. 

It may be a bug in the physics engine, but not our bug or anything we can do about. We don't calculate the physics. However, if you're running into lack of floating point precision, that's not a bug, that's on the gamedev for managing the right variable types and precision.

> I'll have to look into how debugging collisions in godot works and get back to you, I haven't tried that before.

I referred you to the right document.

**Comment by ell1e** [comment]
Thanks for your input!

As a side note on the ray length, I previously tried using the minimum to maximum height reported from `.get_aabb` on a `.bake_mesh` result from the Terrain3D, but it seems to have a different offset or scale than to what's actually on the screen. Therefore, I had to fall back to something that would likely cover all maps encountered. It would be useful to add something to the API to get the real world coordinates, actual bounding box [e.g. to the list of methods here](https://terrain3d.readthedocs.io/en/latest/api/class_terrain3d.html#methods). My apologies if that is already found somewhere, but it doesn't seem to be.

Since the collision mesh looks to be covering those bugged out hills as intended, as per your suggestion I forwarded this issue now: https://github.com/godotengine/godot/issues/95458

**Comment by TokisanGames** [comment]
What about the other testing I asked about, testing Jolt and 4.3rc3?

What about testing your posted code on our demo? 

What about running a player character over the problem areas. Is it just rays or body collision also? 

You're going to need more testing and analysis to get a good response from Godot devs on that ticket. Its not that they don't care, but the ticket lacks testing, an MRP, and isn't reproducible for anyone else to test in order to identify and fix the problem. 

Physics works fine with Terrain3D for everyone else. So telling them the steps to reproduce the problem is to use Terrain3D and run vertical rays is not something they can do and get your same result. 

A good ticket for Godot includes a reproducible problem, with an MRP unless it is obvious without one, and a lot of testing to determine the specific conditions that cause it. And testing the latest version as it may have already been fixed. If it works in jolt and not Godot, that's a good issue for physics also.
