### ISSUE TITLE
Cannot change textures with paint tool

### ISSUE THREAD

**Issue by bugbountyguy** [TokisanGames/Terrain3D#484]
### Terrain3D version

v0.9.2

### System information

Godot v4.3 (not .net), Linux, Vulkan

### Is the issue reproducable in the demo?

Yes

### Issue description

No matter how much I change the textures I only seem to be able to paint the 'base' texture with id 0. I'm wondering if this is a bug with v4.3 or maybe linux for this plugin... Unsure, but I've got it installed via the plugin menu. Watched the texture part of the tutorial videos and looks like it must be a bug since I followed the same steps to apply the textures. When playing with the scaling settings, that's how I noticed it just kept painting the base texture instead of the secondary, no matter how I selected it.

**Comment by TokisanGames** [comment]
4.3 works fine for most everyone else.
Are you using the Forward+ renderer? Compatibility is not supported.
Is there any information in your console?
What card?
When painting is `Texture` enabled? Disabling it allows you to paint scale/rotation only without changing textures.
You can paint base with id 0. What happens when you paint base with id 1+
What about spraying with 100% strength with id1+?
