### ISSUE TITLE
modify terrain data in real-time with code,like:gdscript、c#

### ISSUE THREAD

**Issue by whutwxn** [TokisanGames/Terrain3D#526]
### Description

How can we create 3D terrain, modify terrain data in real-time, and modify textures through code? Do you have any example code

**Comment by whutwxn** [comment]
The file（CodeGenerated.gd） code writing is too simple

**Comment by TokisanGames** [comment]
The API is full of documentation on how to do this. Please spend more time reading through it. e.g. 
* [Set base texture](https://terrain3d.readthedocs.io/en/latest/api/class_terrain3ddata.html#class-terrain3ddata-method-set-control-base-id) 
* [Create a hole](https://terrain3d.readthedocs.io/en/latest/api/class_terrain3ddata.html#class-terrain3ddata-method-set-control-hole)
* [Set individual bits](https://terrain3d.readthedocs.io/en/latest/api/class_terrain3dutil.html)
* The [control map format](https://terrain3d.readthedocs.io/en/latest/docs/controlmap_format.html)

Ask on discord for specific help.

**Comment by TokisanGames** [comment]
Let us know if you have specific questions and join us on [discord](https://tokisan.com/discord).

**Comment by whutwxn** [comment]
When I update the height map and control map in real-time in the game to ensure real-time map drawing, the FPS of the game drops directly to around 10, but the CPU, GPU, and memory usage are not very high. What is the reason for this？

**Comment by whutwxn** [comment]
![image](https://github.com/user-attachments/assets/fca059ca-4cd3-4daf-b4fb-be0af8d8422e)
this is the code

**Comment by TokisanGames** [comment]
* If you have collision enabled, updating the heightmap is rebuilding the collision for every region, which is slow. Disable collision generation for testing at least. Dynamic collision #278 will alleviate this. 
* You don't need to set_pixels and most definitely should not be force_updating_maps hundreds of times per second. Switch to physics_process for pixel updates at 60fps. And update maps no more than 6-10x/second which can be achieved with a basic timer at 0.1 seconds.
* It's faster to access and write to the image maps directly rather than using set_pixel. This should be done when accessing a large number of pixels, and certainly if you're doing it hundreds of times per second. https://terrain3d.readthedocs.io/en/latest/docs/collision.html#query-many-heights
* It's clear you're using _process as your main driver, but you should rarely use _process. Your structure needs a redesign. Updates on timer like I mentioned, stop doing redundant things like checking variables and using set_pixel for the same values hundreds of times per second. Verify things only at the start of an operation, then only perform data writes in the loop. Then batch map updates periodically. _process is a loop and you're using it poorly which gives you terrible performance.
